### ISSUE TITLE
Possible conflict with Yoast on RCP plugin activation

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1661]
From a customer:

```
Fatal error: Uncaught Error: Call to undefined function rcp_is_stripe_subscriber() in /var/www/html/wp-content/plugins/restrict-content-pro/includes/member-functions.php:1212
Stack trace: #0 /var/www/html/wp-content/plugins/restrict-content-pro/includes/shortcodes.php(520): rcp_member_can_update_billing_card()
#1 /var/www/html/wordpress/wp-includes/shortcodes.php(319): rcp_update_billing_card_shortcode('', '', 'rcp_update_card')
#2 [internal function]: do_shortcode_tag(Array)
#3 /var/www/html/wordpress/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(rcp_up...', 'do_shortcode_ta...', '[rcp_update_car...')
#4 /var/www/html/wordpress/wp-includes/class-wp-hook.php(286): do_shortcode('[rcp_update_car...')
#5 /var/www/html/wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters('[rcp_update_car...', Array)
#6 /var/www/html/wp-content/plugins/wordpress-seo/admin/links/class-link-watcher.php(114): apply_filters('the_content', '[rcp_update_car...')
#7 /var/www/html/wp-content/plugins/wordpress-seo/admin/li in /var/www/html/wp-content/plugins/restrict-content-pro/includes/member-functions.php on line 1212
```

Maybe a conflict with their link watcher feature?

The customer said he got a fatal error with the above stack trace the first time he tried to activate RCP. When he tried again a second time it worked fine.

Haven't yet tested/reproduced this myself. Just want to make a note of it.

**Comment by mindctrl** [comment]
That's weird. As far as I can see, that link watcher only runs on the `save_post` hook. 

https://plugins.svn.wordpress.org/wordpress-seo/trunk/admin/links/class-link-watcher.php

**Comment by pippinsplugins** [comment]
My guess would be that it's running when `member-functions.php` hasn't been loaded but `shortcodes.php` has been.

**Comment by nosegraze** [comment]
@mindctrl On install we use `wp_insert_post()` to create the default pages. That function calls `save_post` at the very end.

**Comment by 84em** [comment]
I experienced the same error upon initial plugin activation.  Activating it a 2nd time worked.

**Comment by tnorthcutt** [comment]
@84em do you mind sharing which version of each (RCP & Yoast) you were using?

**Comment by 84em** [comment]
@tnorthcutt sure thing. RCP 2.9.10 and Yoast 7.0.3

**Comment by tnorthcutt** [comment]
@84em thank you!

**Comment by tnorthcutt** [comment]
(probably) related: https://github.com/WordImpress/Give/pull/1852

**Comment by mindctrl** [comment]
Got another report of this.

**Comment by chrisvanpatten** [comment]
I got this today as well. Was able to experience it in a few environments. Will see if I can reproduce it tomorrow...

**Comment by pkirk** [comment]
Just got that error:
RCP 2.9.13
Yoast 7.8
